// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyRPJRRtBh8gPaIIJ30f9W8FnR3fH346o',
    appId: '1:301303810768:web:7b886d8069435ebf11ecd5',
    messagingSenderId: '301303810768',
    projectId: 'kkaetalk',
    authDomain: 'kkaetalk.firebaseapp.com',
    storageBucket: 'kkaetalk.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtIvf9fi2A_Zu7cQ9XoQdwlfsbN2hXUmU',
    appId: '1:301303810768:android:fa508f475291126911ecd5',
    messagingSenderId: '301303810768',
    projectId: 'kkaetalk',
    storageBucket: 'kkaetalk.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQfgrehbhFrIprFwPNjcgaVDo6lcG5R04',
    appId: '1:301303810768:ios:ac5dea364650a40211ecd5',
    messagingSenderId: '301303810768',
    projectId: 'kkaetalk',
    storageBucket: 'kkaetalk.firebasestorage.app',
    iosBundleId: 'com.example.kkaetalk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQfgrehbhFrIprFwPNjcgaVDo6lcG5R04',
    appId: '1:301303810768:ios:ac5dea364650a40211ecd5',
    messagingSenderId: '301303810768',
    projectId: 'kkaetalk',
    storageBucket: 'kkaetalk.firebasestorage.app',
    iosBundleId: 'com.example.kkaetalk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCyRPJRRtBh8gPaIIJ30f9W8FnR3fH346o',
    appId: '1:301303810768:web:f62ca8eff74d166e11ecd5',
    messagingSenderId: '301303810768',
    projectId: 'kkaetalk',
    authDomain: 'kkaetalk.firebaseapp.com',
    storageBucket: 'kkaetalk.firebasestorage.app',
  );
}
